version: '3.9' # optional since v1.27.0

services:
    redis:
        image: redis
        container_name: redis
        ports:
            - 6379:6379

    counter-service:
        build: .
        container_name: counter-service
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis
        ports:
            - 3000:3000


