version: '3.9' # optional since v1.27.0

services:
    redis:
        image: redis
        container_name: redis
        ports:
            - 6379:6379

    # counter-service
    counter-service:
        # build: .
        image: counter-service
        container_name: counter-service
        depends_on:
            - redis
        # environment:
        # restart: always
        ports:
            - 3000:3000


