version: '3.9'

services:
    redis:
        image: redis
        container_name: redis
        ports:
            - 6379:6379

    app:
        build: app
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis

    nginx:
        container_name: nginx
        build: nginx
        ports:
            - 80:80
        depends_on:
            - app


